name: expense_new_ui
description: .
publish_to:
version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.6
  sqflite: ^2.0.0+4
  rxdart: ^0.27.3
  flutter_bloc: ^8.0.0
  equatable: ^2.0.3
  shared_preferences: ^2.0.8


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
